Update defi.tokenlist.json
pangolindex/tokenlists pull request #128
Opened 2021-09-26 02:44 UTC by DrZee3

Add ICEDOGE token

2021-09-26 04:32 UTC, SarjuHansaliya requested changes

2021-09-26 04:32 UTC, SarjuHansaliya commented on defi.tokenlist.json
> +                {
1. invalid json at 566th line
2. needs proper formatting at 567th line

2021-09-29 07:38 UTC, SarjuHansaliya commented
@DrZee3 can you please resolve conflicts in this PR ?

2021-09-29 14:17 UTC, bmino requested changes

2021-09-29 14:17 UTC, bmino commented on defi.tokenlist.json
> +>>>>>>> main
This shouldn't be here. Looks like it's left behind from some previous merge conflict resolution?

2021-09-29 14:17 UTC, bmino commented on defi.tokenlist.json
> +        },
This is now invalid JSON missing an opening bracket

2021-09-29 14:17 UTC, bmino commented on defi.tokenlist.json
> +
Please remove this line break

2021-09-29 14:20 UTC, bmino commented
I think it's missing a chainId too

2021-09-29 15:45 UTC, bmino commented
Formatting looks good now. You'll need to update the minor version and timestamp as per the [README](https://github.com/pangolindex/tokenlists#adding-your-token)

2021-09-29 16:38 UTC, DrZee3 commented
> Formatting looks good now. You'll need to update the minor version and timestamp as per the [README](https://github.com/pangolindex/tokenlists#adding-your-token)

thank you bmino. just updated, please check. hope its fine

2021-09-29 17:10 UTC, bmino approved these changes

2021-09-29 17:13 UTC, SarjuHansaliya approved these changes

2021-09-29 17:14 UTC, merged