Fuji token list
pangolindex/tokenlists pull request #15
Opened 2021-04-04 06:51 UTC by HariSeldon23

I've added a Fuji token list which will allow us to run test simulations on Fuji.

This will help us when we're testing contracts that utilise other tokens, for example ChainLink.

2021-04-04 07:18 UTC, benber86 requested changes
No love for WAVAX?
0xd00ae08403B9bbb9124bB305C09058E32C39A48c

2021-04-12 15:08 UTC, dasconnor commented
Can you add a blurb about this list to the readme? Otherwise looks good.

2021-06-07 00:20 UTC, bmino commented
Thanks @cgcardona for that addition!
@HariSeldon23 it looks like this list contains more tokens on Fuji than the now existing list added by cgcardona. Should this replace that list? There appears to be 2 tokens on the current fuji list as examples:

1. FUJISTABLE
2. FUJIMOON

2021-06-07 00:41 UTC, cgcardona commented
IMO we shouldn't merge this PR because it's unwise to use the token names of existing projects to avoid confusing people and to avoid upsetting those teams. That was my intention behind creating the existing fuji token list w/ FUJIMOON and FUJISTABLE. I created those tokens and fuji pangolin liquidity pairs w/ that in mind.

2021-06-07 00:51 UTC, bmino commented
> IMO we shouldn't merge this PR because it's unwise to use the token names of existing projects to avoid confusing people and to avoid upsetting those teams. That was my intention behind creating the existing fuji token list w/ FUJIMOON and FUJISTABLE. I created those tokens and fuji pangolin liquidity pairs w/ that in mind.

you would prefer to allow the token creators themselves to add to this list? I think @HariSeldon23's intention is to start a curated list of tokens on fuji for ease of use looking for tokens. maybe difficult when there are multiple copies of some popular token names

2021-06-07 00:55 UTC, cgcardona commented
Yes I think actual token creators should create a PR to add their tokens to the existing fuji token list. It will avoid the headache and confusion in the future from using other people's brands.

2021-06-07 00:57 UTC, bmino commented
I agree with @cgcardona here. thoughts @HariSeldon23

2021-06-07 01:07 UTC, HariSeldon23 commented
This all sounds perfectly reasonable. Sounds good 👍

2021-06-07 01:30 UTC, bmino commented
Alright, sounds good. I'm closing this after the above conversation

2021-06-07 01:30 UTC, closed without merging